- include_vars: ../jenkins_slave/defaults/my_var.yml

- name: Copying Jenkins repo
  get_url:
     url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
     dest: /etc/yum.repos.d/

- name: Adding the repository gpg keys
  rpm_key:
     key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
     state: present

- name: Removing Old Java_1.7 version
  yum:
    name: java-1.7.0
    state: absent

- name: Installing Jenkins Entered Veriosn and other packages
  yum:
    name: "{{item}}"
    state: present
    enablerepo: epel
  with_items:
        - git
        - java-1.8.0
        - ansible
        - docker
        - curl

- name: Assigning shell to jenkins user
  user:
    name: jenkins
    comment: "jenkins Slave"
    shell: /bin/bash
    home: "{{ jenkins_user_home }}"

#- name: Copying Jenkins Skell file in jenkins users home dir
#  shell: "cp /etc/skel/.bash* /var/lib/jenkins"

- file:
    path: "{{ jenkins_user_home }}/.ssh"
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- file:
    path: "{{ jenkins_home }}"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Add user Public Key
  copy:
     src: "../jenkins_slave/files/jenkins_id_rsa.pub"
     dest: "{{ jenkins_user_home }}/.ssh/id_rsa.pub"
     mode: 0644
     owner: "{{ username }}"
     group: "{{ username }}"

- name: Add user Private Key
  copy:
     src: "../jenkins_slave/files/jenkins_id_rsa"
     dest: "{{ jenkins_user_home }}/.ssh/id_rsa"
     mode: 0600
     owner: "{{ username }}"
     group: "{{ username }}"

- name: Add user Private Key
  copy:
     src: "../jenkins_slave/files/jenkins_id_rsa.pub"
     dest: "{{ jenkins_user_home }}/.ssh/authorized_keys"
     mode: 0600
     owner: "{{ username }}"
     group: "{{ username }}"

- name: Adding Bitbucket Public Key
  copy:
     src: "../jenkins_slave/files/bitbucket_pub"
     dest: "{{ jenkins_user_home }}/.ssh/known_hosts"
     mode: 0644
     owner: "{{ username }}"
     group: "{{ username }}"

- name: git config user name
  shell: git config --global user.name "{{ git_name }}" executable=/bin/bash
  become: yes
  become_user: "{{ username }}"

- name: git config user email
  shell: git config --global user.email "{{ git_email }}" executable=/bin/bash
  become: yes
  become_user: "{{ username }}"

- file:
    path: "{{ jenkins_user_home }}/.m2"
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory


## Installing and configuring Maven
- name: Downloading maven-3.3.9 tar file
  get_url:
     url: "{{Maven_Package}}"
     dest: /tmp/

- name: Extracting Maven tar file
  shell: "tar -xvf /tmp/apache-maven-3.3.9-bin.tar.gz -C {{ jenkins_user_home }}/.m2"

- name: Extracting Maven tar file
  shell: "alternatives --install /usr/bin/mvn mvn {{ jenkins_user_home }}.m2/apache-maven-3.3.9/bin/mvn 1"



## Installing jdk
- name: Downloading jdk1.8.0_131 rpm package
  shell: "wget --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm"

- name: Installing jdk1.8.0_131 rpm packag
  yum:
    name: jdk-8u131-linux-x64.rpm
    state: present


## Giving sudo access for Jenkins User
- name: Setup jenkins user in sudoers file for full access.
  lineinfile:
    path: /etc/sudoers
    line: "{{ item }}"
  with_items:
    - '{{username}} ALL=(ALL)       NOPASSWD: ALL'
    - 'Defaults:{{username}}  !requiretty'

## configuring pip and Upgrading awscli, boto and boto3
- name: Downloading and configuring pip. Upgrading awscli and installing boto
  shell: "curl -O https://bootstrap.pypa.io/get-pip.py;export PATH=~/.local/bin:$PATH;python get-pip.py --user;~/.local/bin/pip install boto;~/.local/bin/pip install boto3;~/.local/bin/pip install awscli --upgrade"

## Instaling repo and npm packge
- name: Installing npm repository
  shell: "curl --silent --location {{npm_repo_shell}} | bash -"

- name: Installing nodejs from npm and node
  yum:
    name: "{{nodejs_version}}"
    state: present

##Adding variable for jenkins user in .bashrc file
- name: Adding JAVA and m2 or maven variable for jenkins user
  lineinfile:
    path: "{{jenkins_user_home}}/.bashrc"
    line: "{{ item }}"
  with_items:
    - 'export JAVA_HOME={{JAVA_HOME}}'
    - 'export _JAVA_OPTIONS={{JAVA_OPTIONS}}'
    - 'export M2_HOME={{M2_HOME}}'
    - 'export PATH=$PATH:{{M2_bin}}'

- name: Adding existing user '{{ username }}' to group docker
  user: name='{{username}}'
        groups=docker
        append=yes

- name: Enabling and start Docker service
  service:
    name: docker
    state: started
    enabled: yes


### Downloading kubectl command
- name: Downloading kubectl command
  shell: "curl -LO {{Kubectl_Package}}; chmod +x kubectl; mv kubectl /usr/local/bin/"


### Downloading Terraform command
- name: Downloading terraform {{Terraform_Version}}
  shell: "wget -N {{Terraform_Zip}}"

- name: Extracting Terraform zip file
  shell: "unzip *.zip"

- name: Moving terraform bin. in bin dir
  shell: "mv terraform /usr/local/bin/"

